### PR TITLE
Fix for Nette 2.2, undefined rules[id].op

### PR DESCRIPTION
**Pull request by ghost**
This fix prevents gist from throwing errors in Nette 2.2. It also keeps this JS compatible with older Nette version.

### CODE REVIEW

**Comment by redhead** [comment]
When does this happen? I can see no `[0]` in the original file for 2.2.

**Comment by ghost** [comment]
I had installed this in Nette 2.2 and there was an undefined property `rules.op`. To prevent that error, I had to verify whether the `rules.op` exists and if not, `rules[0].op` must be used instead.
Happened in: Google Chrome 34.0.1847.132

**Comment by pavelplzak** [comment]
Thanks a lot!

**Comment by mafikes** [comment]
validation "email" not working.

**Pull request merged**
